### PR TITLE
[#32] Dans les tests adaptatifs, on donne les challenges qui sont dans des tubes faciles en priorité (US-1073)

### PR DESCRIPTION
**Pull request by jilljenn**
Ajouté deux tests, fix un 😄

### CODE REVIEW

**Comment by jilljenn** [comment]
Il manquait un point-virgule (._.)

**Comment by mackwic** [comment]
I've deployed this PR to http://1073-easy-tubes-first.pix-dev.ovh . Please check it out

**Comment by mackwic** [comment]
I've deployed this PR to http://1073-easy-tubes-first.pix-dev.ovh . Please check it out

**Comment by mackwic** [comment]
I've deployed this PR to http://1073-easy-tubes-first.pix-dev.ovh . Please check it out

**Comment by mackwic** [comment]
I've deployed this PR to http://1073-easy-tubes-first.pix-dev.ovh . Please check it out

**Pull request closed without merging**
